### ISSUE TITLE
[Feature Request] Add .Rating() support for CVSS 2.0

### ISSUE THREAD

**Issue by zenire** [pandatix/go-cvss#4]
CVSS 3.0 and above support the `.Rating()` function but CVSS 2.0 doesn't in this package.
It would be nice if this package supported it for CVSS 2.0 according to the NVD Vulnerability Severity Ratings: https://nvd.nist.gov/vuln-metrics/cvss

**Comment by pandatix** [comment]
Hello, thanks for opening this issue and a PR.

Indeed, there is no implementation for the `Rating` function in the CVSS v2.0 submodule `github.com/pandatix/go-cvss/20`.
This is due to the fact that CVSS v2.0 does not support rating as part of [the FIRST.ORG specification](https://www.first.org/cvss/v2/guide).
The NVD extends this specification to create their own rating system.

The following comes from the link you provided.
>  NVD provides qualitative severity ratings of "Low", "Medium", and "High" for CVSS v2.0 base score ranges in addition to the severity ratings for CVSS v3.0 as they are defined in the CVSS v3.0 specification.

As the implementation does not consider CVSS extensions (e.g. CVSS v2.0 from NVD, CVSS-A...), I regret to inform you this won't be added.
Notice it is scheduled to be part of CVSS v4.0, if this may help you for future use cases.

I let this issue open for discussions if you consider this MUST be part of the project regarding the information I provided.
If the problem is from the specification, you can send an e-mail to cvss@first.org such that we would discuss it next CVSS SIG Meeting and provide an official answer.

**Comment by zenire** [comment]
Thank you for your quick answer and explanation! I understand, and it's best to stick to the FIRST.ORG specification. I'll add custom code in my project to extend the specification with NVD.

I'll close this issue from my side unless there are other opinions.
